### ISSUE TITLE
Could not GET 'https://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/com.rsa.jsafe/3.6/com.rsa.jsafe-3.6.pom'. Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by topolik** [holatuwol/liferay-intellij#8]
Hi Minhchau,

The problem lies here:
https://github.com/holatuwol/liferay-intellij/blob/4bcdbcdf3b50632c573cbc02a01cbd2a07fe0a7d/streams9/streams9.js#L506

The tool expects 7.0.x-private branch to be fresh fetched (up-to-date with upstream) which is not the case for 7.2.x-private and 7.1.x-private branches. I guess there's a reason the tool doesn't read the file directly from the disk?

Thanks.

**Comment by topolik** [comment]
Forgot to mention the workaround is to `git fetch upstream 7.0.x-private`

**Comment by holatuwol** [comment]
@topolik : Yeah, the file on disk can be wrong when you're working with older tags. I'll push an update to iterate over the different private branch and choose the most up-to-date one for `git show`.
